scraper:
  users:
    - username: elonmusk
    - username: jack
  http:
    #proxies:
    #  - "socks5://localhost:9050"
    timeout: 15s

schedulers:
  tweet_scraper:
    enabled: true
    delay: 5m
    jitter: 2m30s
    initial:
      delay: 2m
      jitter: 1m30s
  tweet_deleted:
    enabled: true
    concurrency_limit: 15
    delay: 30m
    jitter: 5m
    initial:
      delay: 1m30s
      jitter: 30s
    ensure_deleted:
      enabled: true
      retries: 15
      delay: 10s
      jitter: 5s
  tweet_archiver:
    enabled: true
    concurrency_limit: 5
    delay: 3m
    jitter: 1m30s

persistence:
  concurrency_limit: 2
  mongodb:
    uri: "mongodb://localhost:27017"
    #uri: "mongodb://{user}:{password}@localhost:27017"
    #authentication:
    #  user: "admin"
    #  password: "admin"
    database: "twitterscraper"
    collections:
      #user_tweets: "tweets-{year}-{month}"
      user_tweets: "tweets"
      kv: "_kv"

archivers:
  archivetoday:
    http:
      timeout: 5m
