"""Initial

Revision ID: c34a1579b569
Revises: 
Create Date: 2022-03-05 15:39:06.896693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c34a1579b569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_historic',
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp_created', sa.Integer(), nullable=False),
    sa.Column('timestamp_finalized', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('userid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_scan_timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tweets',
    sa.Column('tweet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('last_review_timestamp', sa.Integer(), nullable=True),
    sa.Column('deletion_detected_timestamp', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.create_index(op.f('ix_tweets_timestamp'), 'tweets', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_timestamp'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_table('profiles')
    op.drop_table('jobs_historic')
    # ### end Alembic commands ###
